apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ms-discovery
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://github.com/Lemjidmayssa/k8s-manifests'
    path: '.'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
