apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ms-custom
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://ton-repo-git'
    path: 'chemin-vers-les-manifestes'
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
